version: '{build}'

configuration: Release

environment:
   # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

install:
- ps: scripts\Get-Deps.ps1

before_build:
- dotnet --info
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build --no-restore -c %CONFIGURATION%

test:
  assemblies:
    only:
      - '**\*.Tests.dll'
  categories:
    except:
    - DoNotRunOnAppVeyor

after_test:
- : |
    dotnet pack --no-restore -c %CONFIGURATION%
    set OUTDIR=build\npm
    set SRCDIR=build\packages
    mkdir %OUTDIR% >nul 2>nul || ver>nul
    for /f "delims=" %%d in ('dir /b /a:d %SRCDIR%') do (pushd %SRCDIR%\%%d && for /f "delims=" %%f in ('call npm pack --quiet') do move %%f ..\..\npm\%%f && popd)

artifacts:
- path: build\npm\*.tgz
  name: Npm
