version: '{build}'

configuration: Release

environment:
   # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- .\build -c %CONFIGURATION%

test:
  assemblies:
    only:
      - '**\*.Tests.dll'
  categories:
    except:
    - DoNotRunOnAppVeyor

after_test:
- .\pack -c %CONFIGURATION%

artifacts:
- path: upm-ci~\packages\*
  name: npm
- path: build\nuget\**\*nupkg
  name: nuget
