name: Build, Test, Pack, Publish

on:
  push:
    tags:
      - v[0-9]+.[0-9]+*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.301
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - name: Build
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      run: ./build.sh -r
    - name: Test
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      run: ./test.sh -r
    - name: Pack
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      run: ./pack.sh -r
    - name: Publish
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./publish.sh -r -g
